In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('data/tmdb_5000_movies.csv')
credits = pd.read_csv('data/tmdb_5000_credits.csv')

In [3]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
movies.shape

(4803, 20)

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies = movies.merge(credits,on='title')

# Not Important feature for Movie recommender system

1. budget
2. homepage
3. id
4. original_language
5. original_title
6. popularity
7. production_comapny
8. production_countries
9. release-date(not sure)

In [7]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies = movies.dropna()

In [12]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [13]:
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4803,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4804,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4805,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4806,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4807,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [14]:
movies.duplicated().sum()

np.int64(0)

In [15]:
import ast

In [19]:
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [16]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [17]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [21]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [22]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [23]:
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4803,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4804,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[Edward Burns, Kerry Bishé, Marsha Dietlein]","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4805,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4806,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton]","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4807,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [24]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [25]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [26]:
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
3012,20616,Swimfan,Ben Cronin has it all: the admiration of his m...,"[Drama, Thriller]","[competition, coma, infidelity, obsession, bat...","[Jesse Bradford, Erika Christensen, Shiri Appl...",[John Polson]
458,41515,Yogi Bear,"Jellystone Park has been losing business, so g...","[Comedy, Family, Animation, Adventure]","[picnic, sandwich, bear, 3d, yogi]","[Dan Aykroyd, Justin Timberlake, Anna Faris]",[Eric Brevig]
1191,4380,Shall We Dance?,"Upon first sight of a beautiful instructor, a ...","[Drama, Romance, Comedy]","[jealousy, wife husband relationship, dancing ...","[Richard Gere, Jennifer Lopez, Susan Sarandon]",[Peter Chelsom]
2871,14799,For Your Consideration,Three actors learn that their respective perfo...,"[Comedy, Drama]",[],"[Catherine O'Hara, Harry Shearer, Parker Posey]",[Christopher Guest]
4352,76487,The Devil Inside,"In Italy, a woman becomes involved in a series...","[Thriller, Horror]","[rome, exorcism, death, demonic possession, fo...","[Fernanda Andrade, Simon Quarterman, Evan Helm...",[William Brent Bell]

In [27]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [28]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [30]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [31]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [32]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
#new.head()

In [33]:
new

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4803,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4804,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4805,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4806,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4807,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [34]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [36]:
vector = cv.fit_transform(new['tags']).toarray()

In [37]:
vector.shape

(4805, 5000)

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

In [39]:
similarity = cosine_similarity(vector)

In [40]:
similarity

array([[1.        , 0.08980265, 0.05986843, ..., 0.02431083, 0.02777778,
        0.        ],
       [0.08980265, 1.        , 0.06451613, ..., 0.02619813, 0.        ,
        0.        ],
       [0.05986843, 0.06451613, 1.        , ..., 0.02619813, 0.        ,
        0.        ],
       ...,
       [0.02431083, 0.02619813, 0.02619813, ..., 1.        , 0.0729325 ,
        0.04671418],
       [0.02777778, 0.        , 0.        , ..., 0.0729325 , 1.        ,
        0.05337605],
       [0.        , 0.        , 0.        , ..., 0.04671418, 0.05337605,
        1.        ]], shape=(4805, 4805))

In [41]:
similarity[0]

array([1.        , 0.08980265, 0.05986843, ..., 0.02431083, 0.02777778,
       0.        ], shape=(4805,))

In [43]:
new[new['title'] == 'The Lego Movie']

,movie_id,title,tags
744,137106,The Lego Movie,"An ordinary Lego mini-figure, mistakenly thoug..."

In [44]:
new[new['title'] == 'The Lego Movie'].index

Index([744], dtype='int64')

In [45]:
new[new['title'] == 'The Lego Movie'].index[0]

np.int64(744)

In [46]:
enumerate(similarity[0])

In [49]:
sorted(list(enumerate(similarity[0])),reverse=True)

[(4804, np.float64(0.0)),
 (4803, np.float64(0.027777777777777776)),
 (4802, np.float64(0.024310831916315757)),
 (4801, np.float64(0.05270462766947299)),
 (4800, np.float64(0.02457365935914952)),
 (4799, np.float64(0.0)),
 (4798, np.float64(0.05802588531856595)),
 (4797, np.float64(0.020998026278290397)),
 (4796, np.float64(0.0)),
 (4795, np.float64(0.0)),
 (4794, np.float64(0.0)),
 (4793, np.float64(0.0)),
 (4792, np.float64(0.05892556509887895)),
 (4791, np.float64(0.0)),
 (4790, np.float64(0.0)),
 (4789, np.float64(0.0314970394174356)),
 (4788, np.float64(0.022680460581325723)),
 (4787, np.float64(0.0)),
 (4786, np.float64(0.022075539284417398)),
 (4785, np.float64(0.0)),
 (4784, np.float64(0.0)),
 (4783, np.float64(0.0445435403187374)),
 (4782, np.float64(0.0)),
 (4781, np.float64(0.027036903521793755)),
 (4780, np.float64(0.0629940788348712)),
 (4779, np.float64(0.022680460581325723)),
 (4778, np.float64(0.0)),
 (4777, np.float64(0.0)),
 (4776, np.float64(0.05270462766947299)),
 (4775, np.float64(0.0)),
 (4774, np.float64(0.032075014954979206)),
 (4773, np.float64(0.0)),
 (4772, np.float64(0.029934217004462485)),
 (4771, np.float64(0.025717224993681984)),
 (4770, np.float64(0.041666666666666664)),
 (4769, np.float64(0.0)),
 (4768, np.float64(0.0)),
 (4767, np.float64(0.0)),
 (4766, np.float64(0.03823595564509362)),
 (4765, np.float64(0.017972128867239735)),
 (4764, np.float64(0.0)),
 (4763, np.float64(0.0)),
 (4762, np.float64(0.0)),
 (4761, np.float64(0.0)),
 (4760, np.float64(0.0314970394174356)),
 (4759, np.float64(0.0)),
 (4758, np.float64(0.023809523809523808)),
 (4757, np.float64(0.0)),
 (4756, np.float64(0.048112522432468816)),
 (4755, np.float64(0.0)),
 (4754, np.float64(0.027399831217559546)),
 (4753, np.float64(0.0314970394174356)),
 (4752, np.float64(0.0)),
 (4751, np.float64(0.029934217004462485)),
 (4750, np.float64(0.0)),
 (4749, np.float64(0.0)),
 (4748, np.float64(0.0)),
 (4747, np.float64(0.025125945381480302)),
 (4746, np.float64(0.0)),
 (4745, np.float64(0.0)),
 (4744, np.float64(0.0)),
 (4743, np.float64(0.03268602252303067)),
 (4742, np.float64(0.017666631333439334)),
 (4741, np.float64(0.0445435403187374)),
 (4740, np.float64(0.036369648372665396)),
 (4739, np.float64(0.0)),
 (4738, np.float64(0.027036903521793755)),
 (4737, np.float64(0.0)),
 (4736, np.float64(0.0890870806374748)),
 (4735, np.float64(0.0)),
 (4734, np.float64(0.0)),
 (4733, np.float64(0.0)),
 (4732, np.float64(0.0)),
 (4731, np.float64(0.0)),
 (4730, np.float64(0.029934217004462485)),
 (4729, np.float64(0.025125945381480302)),
 (4728, np.float64(0.0)),
 (4727, np.float64(0.0)),
 (4726, np.float64(0.06666666666666667)),
 (4725, np.float64(0.0)),
 (4724, np.float64(0.0)),
 (4723, np.float64(0.0)),
 (4722, np.float64(0.0)),
 (4721, np.float64(0.019641855032959656)),
 (4720, np.float64(0.0)),
 (4719, np.float64(0.029934217004462485)),
 (4718, np.float64(0.0)),
 (4717, np.float64(0.08606629658238703)),
 (4716, np.float64(0.0)),
 (4715, np.float64(0.0)),
 (4714, np.float64(0.0)),
 (4713, np.float64(0.0)),
 (4712, np.float64(0.026028960314767677)),
 (4711, np.float64(0.0)),
 (4710, np.float64(0.02021130208636108)),
 (4709, np.float64(0.0)),
 (4708, np.float64(0.0)),
 (4707, np.float64(0.0)),
 (4706, np.float64(0.02817180849095055)),
 (4705, np.float64(0.012745318548364542)),
 (4704, np.float64(0.0)),
 (4703, np.float64(0.06666666666666667)),
 (4702, np.float64(0.036369648372665396)),
 (4701, np.float64(0.0)),
 (4700, np.float64(0.0)),
 (4699, np.float64(0.036369648372665396)),
 (4698, np.float64(0.032075014954979206)),
 (4697, np.float64(0.0)),
 (4696, np.float64(0.0)),
 (4695, np.float64(0.017282528245507085)),
 (4694, np.float64(0.022680460581325723)),
 (4693, np.float64(0.023338001400466827)),
 (4692, np.float64(0.029934217004462485)),
 (4691, np.float64(0.0)),
 (4690, np.float64(0.029934217004462485)),
 (4689, np.float64(0.025416428388767443)),
 (4688, np.float64(0.0)),
 (4687, np.float64(0.0)),
 (4686, np.float64(0.0)),
 (4685, np.float64(0.0)),
 (4684, np.float64(0.0)),
 (4683, np.float64(0.0)),
 (4682, np.float64(0.0)),
 (4681, np.float64(0.01807753815155468)),
 (4680, np.float64(0.0)),
 (4679, np.float64(0.032075014954979206)),
 (4678, np.float64(0.0)),
 (4677, np.float64(0.0)),
 (4676, np.float64(0.0)),
 (4675, np.float64(0.0)),
 (4674, np.float64(0.029012942659282975)),
 (4673, np.float64(0.028583097523751468)),
 (4672, np.float64(0.12379689211803457)),
 (4671, np.float64(0.049690399499995326)),
 (4670, np.float64(0.0)),
 (4669, np.float64(0.020833333333333332)),
 (4668, np.float64(0.029934217004462485)),
 (4667, np.float64(0.0)),
 (4666, np.float64(0.03268602252303067)),
 (4665, np.float64(0.034020690871988585)),
 (4664, np.float64(0.0)),
 (4663, np.float64(0.030949223029508643)),
 (4662, np.float64(0.0)),
 (4661, np.float64(0.0)),
 (4660, np.float64(0.032075014954979206)),
 (4659, np.float64(0.0)),
 (4658, np.float64(0.0)),
 (4657, np.float64(0.0)),
 (4656, np.float64(0.08838834764831843)),
 (4655, np.float64(0.022473328748774737)),
 (4654, np.float64(0.0)),
 (4653, np.float64(0.09245003270420485)),
 (4652, np.float64(0.0)),
 (4651, np.float64(0.034020690871988585)),
 (4650, np.float64(0.0)),
 (4649, np.float64(0.0)),
 (4648, np.float64(0.0)),
 (4647, np.float64(0.0)),
 (4646, np.float64(0.0222717701593687)),
 (4645, np.float64(0.0445435403187374)),
 (4644, np.float64(0.0)),
 (4643, np.float64(0.0)),
 (4642, np.float64(0.0445435403187374)),
 (4641, np.float64(0.03553345272593507)),
 (4640, np.float64(0.08333333333333333)),
 (4639, np.float64(0.07905694150420949)),
 (4638, np.float64(0.0)),
 (4637, np.float64(0.07106690545187014)),
 (4636, np.float64(0.0)),
 (4635, np.float64(0.05892556509887895)),
 (4634, np.float64(0.043033148291193514)),
 (4633, np.float64(0.027399831217559546)),
 (4632, np.float64(0.026352313834736494)),
 (4631, np.float64(0.036369648372665396)),
 (4630, np.float64(0.0)),
 (4629, np.float64(0.018633899812498245)),
 (4628, np.float64(0.030949223029508643)),
 (4627, np.float64(0.0)),
 (4626, np.float64(0.0)),
 (4625, np.float64(0.09128709291752768)),
 (4624, np.float64(0.0)),
 (4623, np.float64(0.05270462766947299)),
 (4622, np.float64(0.10206207261596575)),
 (4621, np.float64(0.0)),
 (4620, np.float64(0.0)),
 (4619, np.float64(0.025717224993681984)),
 (4618, np.float64(0.0)),
 (4617, np.float64(0.032075014954979206)),
 (4616, np.float64(0.0)),
 (4615, np.float64(0.0)),
 (4614, np.float64(0.0)),
 (4613, np.float64(0.0)),
 (4612, np.float64(0.0)),
 (4611, np.float64(0.0)),
 (4610, np.float64(0.036369648372665396)),
 (4609, np.float64(0.0)),
 (4608, np.float64(0.0)),
 (4607, np.float64(0.0)),
 (4606, np.float64(0.043033148291193514)),
 (4605, np.float64(0.0)),
 (4604, np.float64(0.0)),
 (4603, np.float64(0.03823595564509362)),
 (4602, np.float64(0.0)),
 (4601, np.float64(0.05555555555555555)),
 (4600, np.float64(0.0)),
 (4599, np.float64(0.0)),
 (4598, np.float64(0.0)),
 (4597, np.float64(0.0)),
 (4596, np.float64(0.048112522432468816)),
 (4595, np.float64(0.05270462766947299)),
 (4594, np.float64(0.0)),
 (4593, np.float64(0.041666666666666664)),
 (4592, np.float64(0.0)),
 (4591, np.float64(0.0)),
 (4590, np.float64(0.06950480468569159)),
 (4589, np.float64(0.024845199749997663)),
 (4588, np.float64(0.029012942659282975)),
 (4587, np.float64(0.0)),
 (4586, np.float64(0.046225016352102424)),
 (4585, np.float64(0.0)),
 (4584, np.float64(0.0)),
 (4583, np.float64(0.0)),
 (4582, np.float64(0.0)),
 (4581, np.float64(0.038749212914606423)),
 (4580, np.float64(0.0)),
 (4579, np.float64(0.0)),
 (4578, np.float64(0.0)),
 (4577, np.float64(0.0)),
 (4576, np.float64(0.0)),
 (4575, np.float64(0.026352313834736494)),
 (4574, np.float64(0.030949223029508643)),
 (4573, np.float64(0.0)),
 (4572, np.float64(0.041666666666666664)),
 (4571, np.float64(0.0)),
 (4570, np.float64(0.0)),
 (4569, np.float64(0.03268602252303067)),
 (4568, np.float64(0.029934217004462485)),
 (4567, np.float64(0.08084520834544431)),
 (4566, np.float64(0.0)),
 (4565, np.float64(0.06415002990995841)),
 (4564, np.float64(0.01567868113972662)),
 (4563, np.float64(0.0445435403187374)),
 (4562, np.float64(0.0)),
 (4561, np.float64(0.0)),
 (4560, np.float64(0.0)),
 (4559, np.float64(0.0629940788348712)),
 (4558, np.float64(0.043396303660274624)),
 (4557, np.float64(0.027036903521793755)),
 (4556, np.float64(0.03928371006591931)),
 (4555, np.float64(0.0)),
 (4554, np.float64(0.0445435403187374)),
 (4553, np.float64(0.03823595564509362)),
 (4552, np.float64(0.027036903521793755)),
 (4551, np.float64(0.023809523809523808)),
 (4550, np.float64(0.0)),
 (4549, np.float64(0.0)),
 (4548, np.float64(0.030949223029508643)),
 (4547, np.float64(0.0)),
 (4546, np.float64(0.0)),
 (4545, np.float64(0.0)),
 (4544, np.float64(0.10669739994407998)),
 (4543, np.float64(0.0)),
 (4542, np.float64(0.029012942659282975)),
 (4541, np.float64(0.0445435403187374)),
 (4540, np.float64(0.0)),
 (4539, np.float64(0.029012942659282975)),
 (4538, np.float64(0.0)),
 (4537, np.float64(0.07001400420140048)),
 (4536, np.float64(0.0)),
 (4535, np.float64(0.030429030972509225)),
 (4534, np.float64(0.03726779962499649)),
 (4533, np.float64(0.0)),
 (4532, np.float64(0.05555555555555555)),
 (4531, np.float64(0.018751465015433733)),
 (4530, np.float64(0.0)),
 (4529, np.float64(0.024845199749997663)),
 (4528, np.float64(0.024310831916315757)),
 (4527, np.float64(0.050251890762960605)),
 (4526, np.float64(0.0)),
 (4525, np.float64(0.0)),
 (4524, np.float64(0.021884405476620423)),
 (4523, np.float64(0.0)),
 (4522, np.float64(0.0)),
 (4521, np.float64(0.0)),
 (4520, np.float64(0.0)),
 (4519, np.float64(0.0)),
 (4518, np.float64(0.05892556509887895)),
 (4517, np.float64(0.0)),
 (4516, np.float64(0.0)),
 (4515, np.float64(0.09245003270420485)),
 (4514, np.float64(0.0)),
 (4513, np.float64(0.0)),
 (4512, np.float64(0.0)),
 (4511, np.float64(0.04914731871829904)),
 (4510, np.float64(0.0)),
 (4509, np.float64(0.029012942659282975)),
 (4508, np.float64(0.0)),
 (4507, np.float64(0.0)),
 (4506, np.float64(0.0)),
 (4505, np.float64(0.021516574145596757)),
 (4504, np.float64(0.0)),
 (4503, np.float64(0.0)),
 (4502, np.float64(0.0)),
 (4501, np.float64(0.09245003270420485)),
 (4500, np.float64(0.0)),
 (4499, np.float64(0.0)),
 (4498, np.float64(0.0)),
 (4497, np.float64(0.02817180849095055)),
 (4496, np.float64(0.0)),
 (4495, np.float64(0.0)),
 (4494, np.float64(0.0)),
 (4493, np.float64(0.0)),
 (4492, np.float64(0.0)),
 (4491, np.float64(0.08606629658238703)),
 (4490, np.float64(0.0)),
 (4489, np.float64(0.13608276348795434)),
 (4488, np.float64(0.0)),
 (4487, np.float64(0.0)),
 (4486, np.float64(0.0)),
 (4485, np.float64(0.0)),
 (4484, np.float64(0.034020690871988585)),
 (4483, np.float64(0.02457365935914952)),
 (4482, np.float64(0.0)),
 (4481, np.float64(0.03333333333333333)),
 (4480, np.float64(0.0)),
 (4479, np.float64(0.0)),
 (4478, np.float64(0.0)),
 (4477, np.float64(0.0)),
 (4476, np.float64(0.0)),
 (4475, np.float64(0.0)),
 (4474, np.float64(0.0)),
 (4473, np.float64(0.0)),
 (4472, np.float64(0.08084520834544431)),
 (4471, np.float64(0.07106690545187014)),
 (4470, np.float64(0.0)),
 (4469, np.float64(0.0)),
 (4468, np.float64(0.026688025634181187)),
 (4467, np.float64(0.09284766908852593)),
 (4466, np.float64(0.0)),
 (4465, np.float64(0.020998026278290397)),
 (4464, np.float64(0.0)),
 (4463, np.float64(0.0)),
 (4462, np.float64(0.03928371006591931)),
 (4461, np.float64(0.0)),
 (4460, np.float64(0.0)),
 (4459, np.float64(0.03928371006591931)),
 (4458, np.float64(0.032075014954979206)),
 (4457, np.float64(0.026688025634181187)),
 (4456, np.float64(0.0)),
 (4455, np.float64(0.0)),
 (4454, np.float64(0.0)),
 (4453, np.float64(0.0)),
 (4452, np.float64(0.05270462766947299)),
 (4451, np.float64(0.0)),
 (4450, np.float64(0.08111071056538127)),
 (4449, np.float64(0.026688025634181187)),
 (4448, np.float64(0.0)),
 (4447, np.float64(0.0)),
 (4446, np.float64(0.0)),
 (4445, np.float64(0.026352313834736494)),
 (4444, np.float64(0.0)),
 (4443, np.float64(0.0)),
 (4442, np.float64(0.07453559924999298)),
 (4441, np.float64(0.0)),
 (4440, np.float64(0.0)),
 (4439, np.float64(0.0)),
 (4438, np.float64(0.0)),
 (4437, np.float64(0.0)),
 (4436, np.float64(0.0)),
 (4435, np.float64(0.0)),
 (4434, np.float64(0.0)),
 (4433, np.float64(0.03268602252303067)),
 (4432, np.float64(0.0)),
 (4431, np.float64(0.0)),
 (4430, np.float64(0.08333333333333333)),
 (4429, np.float64(0.0)),
 (4428, np.float64(0.041344911529736156)),
 (4427, np.float64(0.0)),
 (4426, np.float64(0.025416428388767443)),
 (4425, np.float64(0.0)),
 (4424, np.float64(0.0)),
 (4423, np.float64(0.0)),
 (4422, np.float64(0.0)),
 (4421, np.float64(0.02817180849095055)),
 (4420, np.float64(0.034752402342845795)),
 (4419, np.float64(0.029462782549439476)),
 (4418, np.float64(0.0)),
 (4417, np.float64(0.0)),
 (4416, np.float64(0.0)),
 (4415, np.float64(0.0)),
 (4414, np.float64(0.0)),
 (4413, np.float64(0.0)),
 (4412, np.float64(0.030429030972509225)),
 (4411, np.float64(0.07856742013183862)),
 (4410, np.float64(0.0)),
 (4409, np.float64(0.02817180849095055)),
 (4408, np.float64(0.0)),
 (4407, np.float64(0.034020690871988585)),
 (4406, np.float64(0.0)),
 (4405, np.float64(0.029462782549439476)),
 (4404, np.float64(0.19245008972987526)),
 (4403, np.float64(0.0)),
 (4402, np.float64(0.07453559924999298)),
 (4401, np.float64(0.032075014954979206)),
 (4400, np.float64(0.026352313834736494)),
 (4399, np.float64(0.03928371006591931)),
 (4398, np.float64(0.048621663832631515)),
 (4397, np.float64(0.0)),
 (4396, np.float64(0.022473328748774737)),
 (4395, np.float64(0.0)),
 (4394, np.float64(0.0)),
 (4393, np.float64(0.0)),
 (4392, np.float64(0.0)),
 (4391, np.float64(0.025125945381480302)),
 (4390, np.float64(0.0)),
 (4389, np.float64(0.04042260417272216)),
 (4388, np.float64(0.0)),
 (4387, np.float64(0.018294043331615058)),
 (4386, np.float64(0.0)),
 (4385, np.float64(0.0)),
 (4384, np.float64(0.0)),
 (4383, np.float64(0.046225016352102424)),
 (4382, np.float64(0.026352313834736494)),
 (4381, np.float64(0.05143444998736397)),
 (4380, np.float64(0.0)),
 (4379, np.float64(0.029012942659282975)),
 (4378, np.float64(0.0)),
 (4377, np.float64(0.0)),
 (4376, np.float64(0.057166195047502935)),
 (4375, np.float64(0.0)),
 (4374, np.float64(0.050251890762960605)),
 (4373, np.float64(0.0)),
 (4372, np.float64(0.0)),
 (4371, np.float64(0.027036903521793755)),
 (4370, np.float64(0.025125945381480302)),
 (4369, np.float64(0.0)),
 (4368, np.float64(0.05270462766947299)),
 (4367, np.float64(0.041666666666666664)),
 (4366, np.float64(0.0)),
 (4365, np.float64(0.0)),
 (4364, np.float64(0.043033148291193514)),
 (4363, np.float64(0.0)),
 (4362, np.float64(0.0)),
 (4361, np.float64(0.0445435403187374)),
 (4360, np.float64(0.0)),
 (4359, np.float64(0.0)),
 (4358, np.float64(0.024056261216234408)),
 (4357, np.float64(0.023570226039551584)),
 (4356, np.float64(0.06950480468569159)),
 (4355, np.float64(0.0)),
 (4354, np.float64(0.06666666666666667)),
 (4353, np.float64(0.0)),
 (4352, np.float64(0.09245003270420485)),
 (4351, np.float64(0.0)),
 (4350, np.float64(0.03726779962499649)),
 (4349, np.float64(0.0)),
 (4348, np.float64(0.030949223029508643)),
 (4347, np.float64(0.1386750490563073)),
 (4346, np.float64(0.0)),
 (4345, np.float64(0.0)),
 (4344, np.float64(0.0)),
 (4343, np.float64(0.0)),
 (4342, np.float64(0.07293249574894728)),
 (4341, np.float64(0.0)),
 (4340, np.float64(0.029012942659282975)),
 (4339, np.float64(0.0)),
 (4338, np.float64(0.05986843400892497)),
 (4337, np.float64(0.0)),
 (4336, np.float64(0.0)),
 (4335, np.float64(0.16012815380508713)),
 (4334, np.float64(0.027036903521793755)),
 (4333, np.float64(0.0)),
 (4332, np.float64(0.043033148291193514)),
 (4331, np.float64(0.041666666666666664)),
 (4330, np.float64(0.10425720702853739)),
 (4329, np.float64(0.041030496993110906)),
 (4328, np.float64(0.0563436169819011)),
 (4327, np.float64(0.0)),
 (4326, np.float64(0.030429030972509225)),
 (4325, np.float64(0.0)),
 (4324, np.float64(0.02457365935914952)),
 (4323, np.float64(0.03553345272593507)),
 (4322, np.float64(0.0)),
 (4321, np.float64(0.0)),
 (4320, np.float64(0.0)),
 (4319, np.float64(0.06950480468569159)),
 (4318, np.float64(0.03456505649101417)),
 (4317, np.float64(0.0)),
 (4316, np.float64(0.026688025634181187)),
 (4315, np.float64(0.05802588531856595)),
 (4314, np.float64(0.0)),
 (4313, np.float64(0.03955938860646177)),
 (4312, np.float64(0.034020690871988585)),
 (4311, np.float64(0.06537204504606134)),
 (4310, np.float64(0.0)),
 (4309, np.float64(0.0)),
 (4308, np.float64(0.0)),
 (4307, np.float64(0.0)),
 (4306, np.float64(0.0)),
 (4305, np.float64(0.0)),
 (4304, np.float64(0.06154574548966636)),
 (4303, np.float64(0.0)),
 (4302, np.float64(0.0)),
 (4301, np.float64(0.0)),
 (4300, np.float64(0.0)),
 (4299, np.float64(0.04042260417272216)),
 (4298, np.float64(0.026688025634181187)),
 (4297, np.float64(0.0)),
 (4296, np.float64(0.0)),
 (4295, np.float64(0.0)),
 (4294, np.float64(0.0)),
 (4293, np.float64(0.0)),
 (4292, np.float64(0.05555555555555555)),
 (4291, np.float64(0.03333333333333333)),
 (4290, np.float64(0.0)),
 (4289, np.float64(0.07106690545187014)),
 (4288, np.float64(0.0)),
 (4287, np.float64(0.027036903521793755)),
 (4286, np.float64(0.0)),
 (4285, np.float64(0.0)),
 (4284, np.float64(0.0)),
 (4283, np.float64(0.026352313834736494)),
 (4282, np.float64(0.0)),
 (4281, np.float64(0.034020690871988585)),
 (4280, np.float64(0.05270462766947299)),
 (4279, np.float64(0.023338001400466827)),
 (4278, np.float64(0.046225016352102424)),
 (4277, np.float64(0.0)),
 (4276, np.float64(0.019374606457303212)),
 (4275, np.float64(0.0)),
 (4274, np.float64(0.0)),
 (4273, np.float64(0.0)),
 (4272, np.float64(0.0)),
 (4271, np.float64(0.0)),
 (4270, np.float64(0.06537204504606134)),
 (4269, np.float64(0.06085806194501845)),
 (4268, np.float64(0.0)),
 (4267, np.float64(0.0)),
 (4266, np.float64(0.0)),
 (4265, np.float64(0.026028960314767677)),
 (4264, np.float64(0.023112508176051212)),
 (4263, np.float64(0.0)),
 (4262, np.float64(0.027036903521793755)),
 (4261, np.float64(0.026028960314767677)),
 (4260, np.float64(0.026352313834736494)),
 (4259, np.float64(0.0)),
 (4258, np.float64(0.048112522432468816)),
 (4257, np.float64(0.0)),
 (4256, np.float64(0.08838834764831843)),
 (4255, np.float64(0.0)),
 (4254, np.float64(0.0)),
 (4253, np.float64(0.10206207261596575)),
 (4252, np.float64(0.0)),
 (4251, np.float64(0.0)),
 (4250, np.float64(0.0)),
 (4249, np.float64(0.018294043331615058)),
 (4248, np.float64(0.0)),
 (4247, np.float64(0.029462782549439476)),
 (4246, np.float64(0.0222717701593687)),
 (4245, np.float64(0.04042260417272216)),
 (4244, np.float64(0.0)),
 (4243, np.float64(0.05270462766947299)),
 (4242, np.float64(0.0)),
 (4241, np.float64(0.0)),
 (4240, np.float64(0.041666666666666664)),
 (4239, np.float64(0.0)),
 (4238, np.float64(0.0)),
 (4237, np.float64(0.029462782549439476)),
 (4236, np.float64(0.0)),
 (4235, np.float64(0.027777777777777776)),
 (4234, np.float64(0.022473328748774737)),
 (4233, np.float64(0.0)),
 (4232, np.float64(0.018751465015433733)),
 (4231, np.float64(0.0314970394174356)),
 (4230, np.float64(0.0)),
 (4229, np.float64(0.0)),
 (4228, np.float64(0.0)),
 (4227, np.float64(0.10675210253672475)),
 (4226, np.float64(0.0)),
 (4225, np.float64(0.03553345272593507)),
 (4224, np.float64(0.0)),
 (4223, np.float64(0.0)),
 (4222, np.float64(0.016835875742536845)),
 (4221, np.float64(0.0)),
 (4220, np.float64(0.0)),
 (4219, np.float64(0.0)),
 (4218, np.float64(0.0)),
 (4217, np.float64(0.034752402342845795)),
 (4216, np.float64(0.0)),
 (4215, np.float64(0.0)),
 (4214, np.float64(0.0)),
 (4213, np.float64(0.06950480468569159)),
 (4212, np.float64(0.027399831217559546)),
 (4211, np.float64(0.0)),
 (4210, np.float64(0.028583097523751468)),
 (4209, np.float64(0.0)),
 (4208, np.float64(0.029934217004462485)),
 (4207, np.float64(0.0)),
 (4206, np.float64(0.02817180849095055)),
 (4205, np.float64(0.0)),
 (4204, np.float64(0.0)),

In [ ]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x: x[1])

[(0, np.float64(1.0000000000000002)),
 (539, np.float64(0.25724787771376323)),
 (1192, np.float64(0.24873416908154544)),
 (260, np.float64(0.24759378423606915)),
 (1214, np.float64(0.24595492912420727)),
 (507, np.float64(0.24498947175305572)),
 (1916, np.float64(0.24019223070763068)),
 (582, np.float64(0.23809523809523808)),
 (1202, np.float64(0.23717082451262844)),
 (3728, np.float64(0.23570226039551587)),
 (74, np.float64(0.22360679774997894)),
 (1440, np.float64(0.22271770159368698)),
 (3606, np.float64(0.22075539284417395)),
 (322, np.float64(0.21919864974047634)),
 (83, np.float64(0.2187974872468418)),
 (4189, np.float64(0.2182178902359924)),
 (1533, np.float64(0.2166445612065605)),
 (2329, np.float64(0.21428571428571427)),
 (2405, np.float64(0.2135042050734495)),
 (47, np.float64(0.21339479988815996)),
 (61, np.float64(0.2132007163556104)),
 (495, np.float64(0.2132007163556104)),
 (972, np.float64(0.2130032168075646)),
 (942, np.float64(0.20953951903123735)),
 (466, np.float64(0.20851441405707477)),
 (1327, np.float64(0.20851441405707477)),
 (2200, np.float64(0.20309059861498083)),
 (973, np.float64(0.20008168266626025)),
 (1199, np.float64(0.19999999999999998)),
 (151, np.float64(0.19641855032959654)),
 (1273, np.float64(0.196116135138184)),
 (2782, np.float64(0.196116135138184)),
 (2969, np.float64(0.19364916731037085)),
 (4045, np.float64(0.19364916731037082)),
 (4404, np.float64(0.19245008972987526)),
 (36, np.float64(0.1917988185229168)),
 (3325, np.float64(0.1911797782254681)),
 (3536, np.float64(0.1892583246525563)),
 (305, np.float64(0.1889822365046136)),
 (3160, np.float64(0.18856180831641267)),
 (461, np.float64(0.18633899812498245)),
 (1319, np.float64(0.18633899812498245)),
 (150, np.float64(0.18605210188381271)),
 (931, np.float64(0.18569533817705186)),
 (27, np.float64(0.1849000654084097)),
 (2997, np.float64(0.1849000654084097)),
 (220, np.float64(0.18257418583505536)),
 (300, np.float64(0.18220272220337375)),
 (1069, np.float64(0.18220272220337375)),
 (67, np.float64(0.17960530202677488)),
 (301, np.float64(0.17928429140015906)),
 (4, np.float64(0.17791499872137212)),
 (184, np.float64(0.17791499872137212)),
 (373, np.float64(0.17766726362967533)),
 (46, np.float64(0.17407765595569785)),
 (7, np.float64(0.17391639824998364)),
 (2492, np.float64(0.17376201171422898)),
 (2727, np.float64(0.17376201171422898)),
 (1827, np.float64(0.17201561551404662)),
 (52, np.float64(0.1714985851425088)),
 (1342, np.float64(0.1714985851425088)),
 (149, np.float64(0.16933350266692065)),
 (26, np.float64(0.1690308509457033)),
 (1804, np.float64(0.1690308509457033)),
 (661, np.float64(0.16798421022632318)),
 (108, np.float64(0.16666666666666666)),
 (208, np.float64(0.16666666666666666)),
 (838, np.float64(0.16666666666666666)),
 (94, np.float64(0.16343011261515333)),
 (2511, np.float64(0.16343011261515333)),
 (1392, np.float64(0.1617875572323585)),
 (4007, np.float64(0.16169041669088863)),
 (31, np.float64(0.16037507477489604)),
 (581, np.float64(0.16037507477489604)),
 (1295, np.float64(0.16012815380508713)),
 (1379, np.float64(0.16012815380508713)),
 (4335, np.float64(0.16012815380508713)),
 (168, np.float64(0.15811388300841897)),
 (91, np.float64(0.15748519708717798)),
 (3626, np.float64(0.15474611514754322)),
 (311, np.float64(0.15430334996209188)),
 (1961, np.float64(0.15319083833634298)),
 (577, np.float64(0.15214515486254612)),
 (3352, np.float64(0.15214515486254612)),
 (158, np.float64(0.15075567228888181)),
 (502, np.float64(0.15075567228888181)),
 (1353, np.float64(0.15075567228888181)),
 (111, np.float64(0.1496710850223124)),
 (1176, np.float64(0.1496710850223124)),
 (2165, np.float64(0.1496710850223124)),
 (172, np.float64(0.14907119849998596)),
 (490, np.float64(0.14907119849998596)),
 (17, np.float64(0.1481668148335556)),
 (1934, np.float64(0.1474419561548971)),
 (422, np.float64(0.14547859349066158)),
 (505, np.float64(0.14547859349066158)),
 (1484, np.float64(0.14547859349066158)),
 (557, np.float64(0.14506471329641488)),
 (41, np.float64(0.14433756729740646)),
 (84, np.float64(0.14360673947588817)),
 (332, np.float64(0.14291548761875733)),
 (568, np.float64(0.14291548761875733)),
 (2682, np.float64(0.14291548761875733)),
 (56, np.float64(0.14213381090374028)),
 (249, np.float64(0.14213381090374028)),
 (1325, np.float64(0.14213381090374028)),
 (2580, np.float64(0.14213381090374028)),
 (1320, np.float64(0.1414213562373095)),
 (1218, np.float64(0.14085904245475275)),
 (487, np.float64(0.13900960937138318)),
 (187, np.float64(0.1388888888888889)),
 (413, np.float64(0.1388888888888889)),
 (1669, np.float64(0.1386750490563073)),
 (2476, np.float64(0.1386750490563073)),
 (4347, np.float64(0.1386750490563073)),
 (2869, np.float64(0.13867504905630726)),
 (2129, np.float64(0.13736056394868904)),
 (1941, np.float64(0.13699915608779772)),
 (1829, np.float64(0.13608276348795434)),
 (2616, np.float64(0.13608276348795434)),
 (4489, np.float64(0.13608276348795434)),
 (595, np.float64(0.13518451760896877)),
 (1013, np.float64(0.13518451760896877)),
 (3407, np.float64(0.13518451760896877)),
 (3620, np.float64(0.13518451760896877)),
 (342, np.float64(0.13471506281091267)),
 (127, np.float64(0.1338258447578277)),
 (754, np.float64(0.13344012817090595)),
 (1475, np.float64(0.13344012817090595)),
 (68, np.float64(0.13333333333333333)),
 (134, np.float64(0.13333333333333333)),
 (368, np.float64(0.13333333333333333)),
 (1156, np.float64(0.13333333333333333)),
 (2968, np.float64(0.13333333333333333)),
 (3671, np.float64(0.13176156917368248)),
 (1000, np.float64(0.13130643285972254)),
 (1045, np.float64(0.13074409009212268)),
 (1094, np.float64(0.13074409009212268)),
 (1654, np.float64(0.13074409009212268)),
 (2374, np.float64(0.13074409009212268)),
 (3374, np.float64(0.13074409009212268)),
 (3996, np.float64(0.13074409009212268)),
 (740, np.float64(0.1301448015738384)),
 (529, np.float64(0.12858612496840993)),
 (778, np.float64(0.12858612496840993)),
 (1297, np.float64(0.12858612496840993)),
 (1613, np.float64(0.12858612496840993)),
 (483, np.float64(0.12830005981991682)),
 (420, np.float64(0.1270821419438372)),
 (1035, np.float64(0.1270821419438372)),
 (238, np.float64(0.1259881576697424)),
 (939, np.float64(0.1259881576697424)),
 (1737, np.float64(0.1259881576697424)),
 (1743, np.float64(0.1259881576697424)),
 (278, np.float64(0.1256297269074015)),
 (2709, np.float64(0.1256297269074015)),
 (3307, np.float64(0.1256297269074015)),
 (1711, np.float64(0.125)),
 (3216, np.float64(0.125)),
 (432, np.float64(0.12422599874998833)),
 (228, np.float64(0.12422599874998831)),
 (28, np.float64(0.12379689211803457)),
 (1272, np.float64(0.12379689211803457)),
 (4672, np.float64(0.12379689211803457)),
 (95, np.float64(0.12286829679574761)),
 (454, np.float64(0.1228682967957476)),
 (549, np.float64(0.1228682967957476)),
 (50, np.float64(0.1217161238900369)),
 (72, np.float64(0.1217161238900369)),
 (275, np.float64(0.1217161238900369)),
 (579, np.float64(0.1217161238900369)),
 (1978, np.float64(0.1217161238900369)),
 (2071, np.float64(0.1217161238900369)),
 (2864, np.float64(0.1217161238900369)),
 (1508, np.float64(0.1215541595815788)),
 (2543, np.float64(0.12155415958157878)),
 (624, np.float64(0.12126781251816647)),
 (653, np.float64(0.12126781251816647)),
 (808, np.float64(0.12126781251816647)),
 (1571, np.float64(0.12126781251816647)),
 (3145, np.float64(0.1203858530857692)),
 (687, np.float64(0.11973686801784994)),
 (123, np.float64(0.11904761904761904)),
 (692, np.float64(0.11904761904761904)),
 (1275, np.float64(0.11904761904761904)),
 (3405, np.float64(0.11904761904761904)),
 (3628, np.float64(0.11904761904761904)),
 (169, np.float64(0.11785113019775792)),
 (1570, np.float64(0.11785113019775792)),
 (166, np.float64(0.1178511301977579)),
 (232, np.float64(0.1178511301977579)),
 (294, np.float64(0.1178511301977579)),
 (859, np.float64(0.1178511301977579)),
 (1612, np.float64(0.1178511301977579)),
 (5, np.float64(0.11669000700233413)),
 (206, np.float64(0.11669000700233413)),
 (10, np.float64(0.1160517706371319)),
 (87, np.float64(0.1160517706371319)),
 (1029, np.float64(0.1160517706371319)),
 (2579, np.float64(0.1160517706371319)),
 (3006, np.float64(0.1160517706371319)),
 (81, np.float64(0.11547005383792512)),
 (627, np.float64(0.11470786693528086)),
 (1369, np.float64(0.11470786693528086)),
 (2255, np.float64(0.11470786693528086)),
 (2319, np.float64(0.11470786693528086)),
 (3719, np.float64(0.11470786693528086)),
 (3997, np.float64(0.11470786693528086)),
 (199, np.float64(0.11446713662390752)),
 (14, np.float64(0.11433239009500587)),
 (126, np.float64(0.11433239009500587)),
 (508, np.float64(0.11433239009500587)),
 (1193, np.float64(0.11433239009500587)),
 (777, np.float64(0.11340230290662862)),
 (854, np.float64(0.1126872339638022)),
 (900, np.float64(0.1126872339638022)),
 (2446, np.float64(0.1126872339638022)),
 (3496, np.float64(0.1126872339638022)),
 (35, np.float64(0.11180339887498947)),
 (141, np.float64(0.11180339887498947)),
 (325, np.float64(0.11180339887498947)),
 (1520, np.float64(0.11180339887498947)),
 (1717, np.float64(0.11180339887498947)),
 (1723, np.float64(0.11180339887498947)),
 (2630, np.float64(0.11180339887498947)),
 (4015, np.float64(0.11180339887498947)),
 (4132, np.float64(0.11180339887498947)),
 (4200, np.float64(0.11180339887498947)),
 (18, np.float64(0.11135885079684349)),
 (1493, np.float64(0.11135885079684349)),
 (2102, np.float64(0.11135885079684349)),
 (2435, np.float64(0.11135885079684349)),
 (513, np.float64(0.1111111111111111)),
 (1080, np.float64(0.1111111111111111)),
 (1292, np.float64(0.1111111111111111)),
 (2009, np.float64(0.1111111111111111)),
 (3338, np.float64(0.1111111111111111)),
 (3618, np.float64(0.1111111111111111)),
 (4094, np.float64(0.1111111111111111)),
 (102, np.float64(0.11037769642208699)),
 (1017, np.float64(0.11037769642208699)),
 (2756, np.float64(0.11037769642208699)),
 (131, np.float64(0.10959932487023819)),
 (174, np.float64(0.10959932487023819)),
 (266, np.float64(0.10959932487023819)),
 (312, np.float64(0.10959932487023819)),
 (330, np.float64(0.10959932487023819)),
 (2068, np.float64(0.10959932487023819)),
 (3100, np.float64(0.10959932487023819)),
 (4076, np.float64(0.10959932487023819)),
 (403, np.float64(0.10942202738310211)),
 (3053, np.float64(0.1091089451179962)),
 (3779, np.float64(0.1091089451179962)),
 (773, np.float64(0.10910894511799618)),
 (1154, np.float64(0.10910894511799618)),
 (3659, np.float64(0.10910894511799618)),
 (3951, np.float64(0.10910894511799618)),
 (239, np.float64(0.10849075915068655)),
 (295, np.float64(0.10814761408717502)),
 (535, np.float64(0.10814761408717502)),
 (2177, np.float64(0.10814761408717502)),
 (986, np.float64(0.10675210253672475)),
 (4227, np.float64(0.10675210253672475)),
 (139, np.float64(0.10669739994407998)),
 (4544, np.float64(0.10669739994407998)),
 (105, np.float64(0.10660035817780521)),
 (233, np.float64(0.10660035817780521)),
 (476, np.float64(0.10660035817780521)),
 (2452, np.float64(0.10660035817780521)),
 (2517, np.float64(0.10660035817780521)),
 (2558, np.float64(0.10660035817780521)),
 (2758, np.float64(0.10660035817780521)),
 (3837, np.float64(0.10660035817780521)),
 (4195, np.float64(0.10660035817780521)),
 (182, np.float64(0.10540925533894598)),
 (334, np.float64(0.10540925533894598)),
 (1054, np.float64(0.10540925533894598)),
 (3781, np.float64(0.10540925533894598)),
 (33, np.float64(0.10425720702853739)),
 (85, np.float64(0.10425720702853739)),
 (148, np.float64(0.10425720702853739)),
 (715, np.float64(0.10425720702853739)),
 (935, np.float64(0.10425720702853739)),
 (1278, np.float64(0.10425720702853739)),
 (1497, np.float64(0.10425720702853739)),
 (2656, np.float64(0.10425720702853739)),
 (4330, np.float64(0.10425720702853739)),
 (129, np.float64(0.10411584125907071)),
 (510, np.float64(0.10411584125907071)),
 (643, np.float64(0.10411584125907071)),
 (898, np.float64(0.10411584125907071)),
 (1084, np.float64(0.10411584125907071)),
 (1107, np.float64(0.10411584125907071)),
 (3462, np.float64(0.10411584125907071)),
 (307, np.float64(0.10314212462587934)),
 (279, np.float64(0.10286889997472794)),
 (1231, np.float64(0.10286889997472794)),
 (1271, np.float64(0.10286889997472794)),
 (3441, np.float64(0.10286889997472794)),
 (4042, np.float64(0.10286889997472794)),
 (2592, np.float64(0.10286889997472792)),
 (157, np.float64(0.10206207261596575)),
 (263, np.float64(0.10206207261596575)),
 (400, np.float64(0.10206207261596575)),
 (660, np.float64(0.10206207261596575)),
 (781, np.float64(0.10206207261596575)),
 (1299, np.float64(0.10206207261596575)),
 (1938, np.float64(0.10206207261596575)),
 (2657, np.float64(0.10206207261596575)),
 (4253, np.float64(0.10206207261596575)),
 (4622, np.float64(0.10206207261596575)),
 (371, np.float64(0.10166571355506977)),
 (412, np.float64(0.10166571355506977)),
 (473, np.float64(0.10166571355506977)),
 (870, np.float64(0.10166571355506977)),
 (1200, np.float64(0.10166571355506977)),
 (1435, np.float64(0.10166571355506977)),
 (270, np.float64(0.10050378152592121)),
 (410, np.float64(0.10050378152592121)),
 (813, np.float64(0.10050378152592121)),
 (933, np.float64(0.10050378152592121)),
 (1274, np.float64(0.10050378152592121)),
 (1819, np.float64(0.10050378152592121)),
 (1842, np.float64(0.10050378152592121)),
 (1999, np.float64(0.10050378152592121)),
 (2280, np.float64(0.10050378152592121)),
 (292, np.float64(0.1)),
 (389, np.float64(0.1)),
 (530, np.float64(0.1)),
 (920, np.float64(0.1)),
 (1075, np.float64(0.1)),
 (2647, np.float64(0.1)),
 (3091, np.float64(0.1)),
 (3734, np.float64(0.1)),
 (1087, np.float64(0.09960238411119947)),
 (243, np.float64(0.09829463743659808)),
 (785, np.float64(0.09820927516479827)),
 (142, np.float64(0.09805806756909201)),
 (564, np.float64(0.09805806756909201)),
 (791, np.float64(0.09805806756909201)),
 (1404, np.float64(0.09805806756909201)),
 (1470, np.float64(0.09805806756909201)),
 (1585, np.float64(0.09805806756909201)),
 (1682, np.float64(0.09805806756909201)),
 (1752, np.float64(0.09805806756909201)),
 (589, np.float64(0.09724332766526303)),
 (1355, np.float64(0.09724332766526303)),
 (43, np.float64(0.09622504486493763)),
 (618, np.float64(0.09622504486493763)),
 (2484, np.float64(0.09622504486493763)),
 (2792, np.float64(0.09622504486493763)),
 (3152, np.float64(0.09622504486493763)),
 (12, np.float64(0.09622504486493762)),
 (122, np.float64(0.09622504486493762)),
 (236, np.float64(0.09622504486493762)),
 (362, np.float64(0.09622504486493762)),
 (2089, np.float64(0.09622504486493762)),
 (2392, np.float64(0.09622504486493762)),
 (2648, np.float64(0.09622504486493762)),
 (160, np.float64(0.09558988911273406)),
 (1414, np.float64(0.09523809523809523)),
 (23, np.float64(0.0944911182523068)),
 (511, np.float64(0.0944911182523068)),
 (922, np.float64(0.0944911182523068)),
 (1025, np.float64(0.0944911182523068)),
 (1304, np.float64(0.0944911182523068)),
 (2836, np.float64(0.0944911182523068)),
 (3426, np.float64(0.0944911182523068)),
 (479, np.float64(0.09435641951204964)),
 (1920, np.float64(0.09428090415820634)),
 (596, np.float64(0.09335200560186731)),
 (1276, np.float64(0.09335200560186731)),
 (1828, np.float64(0.09335200560186731)),
 (21, np.float64(0.09284766908852593)),
 (242, np.float64(0.09284766908852593)),
 (306, np.float64(0.09284766908852593)),
 (691, np.float64(0.09284766908852593)),
 (794, np.float64(0.09284766908852593)),
 (901, np.float64(0.09284766908852593)),
 (960, np.float64(0.09284766908852593)),
 (978, np.float64(0.09284766908852593)),
 (1002, np.float64(0.09284766908852593)),
 (1247, np.float64(0.09284766908852593)),
 (4467, np.float64(0.09284766908852593)),
 (799, np.float64(0.09259259259259259)),
 (2270, np.float64(0.09245003270420485)),
 (2384, np.float64(0.09245003270420485)),
 (2852, np.float64(0.09245003270420485)),
 (4352, np.float64(0.09245003270420485)),
 (4501, np.float64(0.09245003270420485)),
 (4515, np.float64(0.09245003270420485)),
 (4653, np.float64(0.09245003270420485)),
 (1492, np.float64(0.09157370929912602)),
 (2444, np.float64(0.09147021665807528)),
 (75, np.float64(0.09128709291752768)),
 (112, np.float64(0.09128709291752768)),
 (164, np.float64(0.09128709291752768)),
 (227, np.float64(0.09128709291752768)),
 (315, np.float64(0.09128709291752768)),
 (349, np.float64(0.09128709291752768)),
 (356, np.float64(0.09128709291752768)),
 (369, np.float64(0.09128709291752768)),
 (626, np.float64(0.09128709291752768)),
 (1374, np.float64(0.09128709291752768)),
 (1696, np.float64(0.09128709291752768)),
 (1786, np.float64(0.09128709291752768)),
 (3447, np.float64(0.09128709291752768)),
 (3535, np.float64(0.09128709291752768)),
 (3814, np.float64(0.09128709291752768)),
 (4625, np.float64(0.09128709291752768)),
 (107, np.float64(0.09072184232530289)),
 (170, np.float64(0.09072184232530289)),
 (812, np.float64(0.09072184232530289)),
 (2001, np.float64(0.09072184232530289)),
 (2966, np.float64(0.09072184232530289)),
 (32, np.float64(0.08989331499509895)),
 (45, np.float64(0.08989331499509895)),
 (222, np.float64(0.08989331499509895)),
 (491, np.float64(0.08989331499509895)),
 (541, np.float64(0.08989331499509895)),
 (2494, np.float64(0.08989331499509895)),
 (1, np.float64(0.08980265101338746)),
 (88, np.float64(0.08980265101338746)),
 (121, np.float64(0.08980265101338746)),
 (245, np.float64(0.08980265101338746)),
 (775, np.float64(0.08980265101338746)),
 (894, np.float64(0.08980265101338746)),
 (937, np.float64(0.08980265101338746)),
 (2163, np.float64(0.08980265101338746)),
 (3299, np.float64(0.08980265101338746)),
 (363, np.float64(0.0890870806374748)),
 (381, np.float64(0.0890870806374748)),
 (467, np.float64(0.0890870806374748)),
 (2876, np.float64(0.0890870806374748)),
 (4736, np.float64(0.0890870806374748)),
 (2382, np.float64(0.08883363181483767)),
 (86, np.float64(0.08838834764831843)),
 (96, np.float64(0.08838834764831843)),
 (98, np.float64(0.08838834764831843)),
 (241, np.float64(0.08838834764831843)),
 (547, np.float64(0.08838834764831843)),
 (1111, np.float64(0.08838834764831843)),
 (2243, np.float64(0.08838834764831843)),
 (2247, np.float64(0.08838834764831843)),
 (2300, np.float64(0.08838834764831843)),
 (2790, np.float64(0.08838834764831843)),
 (3089, np.float64(0.08838834764831843)),
 (4256, np.float64(0.08838834764831843)),
 (4656, np.float64(0.08838834764831843)),
 (230, np.float64(0.08830215713766959)),
 (654, np.float64(0.08830215713766959)),
 (1280, np.float64(0.08830215713766959)),
 (1874, np.float64(0.08830215713766959)),
 (103, np.float64(0.08753762190648169)),
 (3439, np.float64(0.08753762190648169)),
 (39, np.float64(0.08703882797784893)),
 (101, np.float64(0.08703882797784893)),
 (203, np.float64(0.08703882797784893)),
 (457, np.float64(0.08703882797784893)),
 (786, np.float64(0.08703882797784893)),
 (814, np.float64(0.08703882797784893)),
 (899, np.float64(0.08703882797784893)),
 (1140, np.float64(0.08703882797784893)),
 (1205, np.float64(0.08703882797784893)),
 (1469, np.float64(0.08703882797784893)),
 (1519, np.float64(0.08703882797784893)),
 (2813, np.float64(0.08703882797784893)),
 (3233, np.float64(0.08703882797784893)),
 (193, np.float64(0.08679260732054925)),
 (501, np.float64(0.08679260732054925)),
 (1824, np.float64(0.08679260732054925)),
 (1617, np.float64(0.08606629658238703)),
 (2161, np.float64(0.08606629658238703)),
 (2246, np.float64(0.08606629658238703)),
 (2335, np.float64(0.08606629658238703)),
 (3067, np.float64(0.08606629658238703)),
 (4162, np.float64(0.08606629658238703)),
 (4491, np.float64(0.08606629658238703)),
 (4717, np.float64(0.08606629658238703)),
 (70, np.float64(0.08574929257125441)),
 (257, np.float64(0.08574929257125441)),
 (746, np.float64(0.08574929257125441)),
 (1159, np.float64(0.08574929257125441)),
 (1267, np.float64(0.08574929257125441)),
 (3026, np.float64(0.08574929257125441)),
 (3138, np.float64(0.08574929257125441)),
 (3308, np.float64(0.08574929257125441)),
 (3387, np.float64(0.08574929257125441)),

# Main Function

In [51]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [52]:
recommend('Gandhi')

Gandhi, My Father
The Wind That Shakes the Barley
A Passage to India
Guiana 1838
Ramanujan